script: |
  cd ~

  if [ ! -d "app" ]; then
    git clone https://github.com/Irfana-2012/aws-monitoring-sre-project.git app
  fi

  cd app
  git pull origin main

  docker stop production-app || true
  docker rm production-app || true
  docker build -t production-app .
  docker run -d -p 3000:3000 --name production-app production-app
