name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~

            if [ ! -d "app" ]; then
              git clone https://github.com/Irfana-2012/aws-monitoring-sre-project.git app
            fi

            cd app
            git pull origin main

            docker stop production-app || true
            docker rm production-app || true
            docker build -t production-app .
            docker run -d -p 3000:3000 --name production-app production-app
